### ISSUE TITLE
Parser Error

### ISSUE THREAD

**Issue by chronaeon** [ConsenSys/surya#73]
```js
surya parse  ../my_audits/mc/**/*.sol

/usr/local/lib/node_modules/surya/node_modules/yargs/yargs.js:1133
      else throw err
           ^
Error
    at new ParserError (/usr/local/lib/node_modules/surya/node_modules/solidity-parser-antlr/dist/index.js:25:16)
    at Object.parse (/usr/local/lib/node_modules/surya/node_modules/solidity-parser-antlr/dist/index.js:71:11)
    at parse (/usr/local/lib/node_modules/surya/lib/parse.js:13:22)
    at Object.require.usage.command.command.command.command.command [as handler] (/usr/local/lib/node_modules/surya/bin/surya:54:5)
    at Object.runCommand (/usr/local/lib/node_modules/surya/node_modules/yargs/lib/command.js:235:44)
    at Object.parseArgs [as _parseArgs] (/usr/local/lib/node_modules/surya/node_modules/yargs/yargs.js:1046:30)
    at Object.get [as argv] (/usr/local/lib/node_modules/surya/node_modules/yargs/yargs.js:989:21)
    at Object.<anonymous> (/usr/local/lib/node_modules/surya/bin/surya:91:3)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
```
**Expected result:**
A parse tree of this rudimentary Metacoin repo from `truffle unbox` (but I get the same error also on more complex contracts.)

**Actual Result:**
A parser error.

This also occurs with the rest of Surya's functions, except for `surya describe` which sort of works (it prints normal output at first), and then throws the same type of error/stack trace at the end.

**What I've Tried:**
```
apt update
apt upgrade
npm install -g yargs
npm uninstall -g surya
npm install -g surya
npm install -g npm
npm install -g solidity-parser-antlr 
npm install -g solc 
npm install -g solidity 
npm install -g ethereum
```
All above updates/installs/uninstalls completed successfully.

* **This error occurs**:
  * on my desktop PC, running `Linux 4.15.0-39 | Ubuntu 18.04 | x86_64`.

* This error **does not occur**:
  * on my laptop PC, running `Linux 4.15.0-39 | Ubuntu 18.04 | x86_64`.
  * on my Android device, running Surya through [termux](https://play.google.com/store/apps/details?id=com.termux&hl=en_US).

The `yargs.js` line in the stack trace points to this snippet:
```js
1115   │       // Check if any of the options to skip validation were provided
1116   │       if (!skipValidation && options.skipValidation.length > 0) {
1117   │         skipValidation = Object.keys(argv).some(key => options.skipValidation.indexOf(key) >= 0 && argv[key] === true)
1118   │       }
1119   │ 
1120   │       // If the help or version options where used and exitProcess is false,
1121   │       // or if explicitly skipped, we won't run validations.
1122   │       if (!skipValidation) {
1123   │         if (parsed.error) throw new YError(parsed.error.message)
1124   │ 
1125   │         // if we're executed via bash completion, don't
1126   │         // bother with validation.
1127   │         if (!argv[completion.completionKey]) {
1124   │ 
1125   │         // if we're executed via bash completion, don't
1126   │         // bother with validation.
1127   │         if (!argv[completion.completionKey]) {
1128   │           self._runValidation(argv, aliases, {}, parsed.error)
1129   │         }
1130   │       }
1131   │     } catch (err) {
1132   │       if (err instanceof YError) usage.fail(err.message, err)
1133   │       else throw err
1134   │     }
```

The `solidity-parser-antlr` line in the stack trace points to this snippet:
```js
  19   │ function ParserError(args) {
  20   │   this.name = 'ParserError';
  21   │   this.message = args.errors.map(function (e) {
  22   │     return e.message;
  23   │   }).join('. ');
  24   │   this.errors = args.errors;
  25   │   this.stack = new Error().stack;
  26   │ }
```

**Comment by chronaeon** [comment]
Turns out I had a malformed request for an mdreport and it used the first element in my glob as the outfile, then the rest of the glob as infiles, hence causing these errors. 

After returning all the infiles to normal, everything should work again.

**Comment by tomarsachin2271** [comment]
What is the solution to this problem?

**Comment by chronaeon** [comment]
Closing as this was user error
